//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManager.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanManager.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friend with the given id was found.
        /// </summary>
        internal static string CantFounFriendWithGivenId {
            get {
                return ResourceManager.GetString("CantFounFriendWithGivenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game with the given id was found.
        /// </summary>
        internal static string CantFounGameWithGivenId {
            get {
                return ResourceManager.GetString("CantFounGameWithGivenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend can&apos;t be empty.
        /// </summary>
        internal static string FriendIsMandatory {
            get {
                return ResourceManager.GetString("FriendIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend name can&apos;t be empty.
        /// </summary>
        internal static string FriendNameIsMandatory {
            get {
                return ResourceManager.GetString("FriendNameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game id can&apos;t be empty.
        /// </summary>
        internal static string GameIsMandatory {
            get {
                return ResourceManager.GetString("GameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game name can&apos;t be empty.
        /// </summary>
        internal static string GameNameIsMandatory {
            get {
                return ResourceManager.GetString("GameNameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre needs to have at least three characters and start with an uppercase letter..
        /// </summary>
        internal static string GenreAtLeastThreeLettersAndFirstLetterUppercaseIsMandatory {
            get {
                return ResourceManager.GetString("GenreAtLeastThreeLettersAndFirstLetterUppercaseIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform needs to have at least twocharacters and start with an uppercase letter..
        /// </summary>
        internal static string PlatformAtLeastTwoLettersAndFirstLetterUppercaseIsMandatory {
            get {
                return ResourceManager.GetString("PlatformAtLeastTwoLettersAndFirstLetterUppercaseIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform name can&apos;t be empty.
        /// </summary>
        internal static string PlatformNameISMandatory {
            get {
                return ResourceManager.GetString("PlatformNameISMandatory", resourceCulture);
            }
        }
    }
}
