version: '3.4'

networks:
  loan_manager-dev:
    driver: bridge 

services:
  loanapi:
    image: loan_manager:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:      
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=loandb;username=loanuser;password=loanuser"
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - loan_manager-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "loanuser"
      POSTGRES_PASSWORD: "loanuser"
      POSTGRES_DB: "loandb"
    networks:
      - loan_manager-dev  
volumes:
  db_volume: